"""The Ledger Protocol — the persistence contract every backend must satisfy.

Structural typing (PEP 544): any object providing these methods IS a Ledger, so
neither backend needs to import the other and services depend only on this
interface. Domain records are typed loosely here (the domain models live in the
application layer today; when they move to operations-domain this Protocol can
import them directly).
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable
from uuid import UUID


@runtime_checkable
class Ledger(Protocol):
    # --- shifts ---
    def create_shift(self, shift): ...
    def get_shift(self, shift_id: UUID): ...
    def list_shifts(self): ...
    def freeze_shift(self, shift_id: UUID): ...

    # --- messages ---
    def add_message(self, message): ...

    # --- events ---
    def add_event(self, event): ...
    def get_event(self, event_id: UUID): ...
    def put_event(self, event): ...

    # --- tasks ---
    def add_task(self, task): ...
    def get_task(self, task_id: UUID): ...
    def put_task(self, task): ...

    # --- corrections (append-only) ---
    def add_correction(self, correction): ...
    def corrections_for(self, record_id: UUID) -> list: ...

    # --- audit (append-only) ---
    def append_audit(self, record) -> None: ...
    def audit_entries_for(self, record_id: str) -> list: ...
