from __future__ import annotations
from typing import Any, Protocol

class ChannelAdapter(Protocol):
    adapter_id: str
    def verify_webhook(self, body: bytes, headers: dict[str, str]) -> bool: ...
    def parse_message(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    async def download_attachment(self, attachment_ref: str) -> bytes: ...
    async def send_message(self, message: dict[str, Any]) -> dict[str, Any]: ...
    async def get_delivery_status(self, provider_message_id: str) -> dict[str, Any]: ...
    async def health_check(self) -> dict[str, Any]: ...
    async def refresh_credentials(self) -> None: ...
