"""Closed V1 enumerations for the governed-retrieval pure package (P4-A1).

Every enum here is a closed set per SPEC R2/R4/R6/R9/R11. No provider,
network, or I/O access. See docs/specs/P4A1_GOVERNED_RETRIEVAL_SPEC.md and
docs/specs/P4A1_GOVERNED_RETRIEVAL_RECEIPT_CONTRACT.md for the normative
source of every literal below.
"""

from __future__ import annotations

from enum import StrEnum


class CorpusId(StrEnum):
    """R4 - the exact three server-registry corpus ids."""

    SHIFT_CONFIRMED_OPERATIONS_V1 = "SHIFT_CONFIRMED_OPERATIONS_V1"
    SHIFT_ADVISORY_MESSAGES_V1 = "SHIFT_ADVISORY_MESSAGES_V1"
    PROJECT_KNOWLEDGE_LOCAL_V1 = "PROJECT_KNOWLEDGE_LOCAL_V1"


class CorpusState(StrEnum):
    """R4 - initial/current corpus availability state."""

    DEPENDENCY_BLOCKED = "DEPENDENCY_BLOCKED"
    LOCAL_ONLY = "LOCAL_ONLY"


class RequestFailureCode(StrEnum):
    """R2 - the exact eight closed structural-validation failure codes."""

    REQUEST_SHAPE_INVALID = "REQUEST_SHAPE_INVALID"
    QUERY_INVALID = "QUERY_INVALID"
    QUERY_LIMIT_EXCEEDED = "QUERY_LIMIT_EXCEEDED"
    CORPUS_ID_INVALID = "CORPUS_ID_INVALID"
    FILTER_INVALID = "FILTER_INVALID"
    FILTER_WIDENS_SCOPE = "FILTER_WIDENS_SCOPE"
    RESULT_LIMIT_INVALID = "RESULT_LIMIT_INVALID"
    CONTEXT_BUDGET_INVALID = "CONTEXT_BUDGET_INVALID"


class FinalOutcome(StrEnum):
    """R11 - the exact ten closed final-outcome discriminators (two literals
    share one RetrievalStoppedV1 variant per the SPEC R11 table)."""

    EVIDENCE_AVAILABLE = "EVIDENCE_AVAILABLE"
    NO_EVIDENCE = "NO_EVIDENCE"
    ACCESS_DENIED = "ACCESS_DENIED"
    CORPUS_UNAVAILABLE = "CORPUS_UNAVAILABLE"
    STALE_EVIDENCE = "STALE_EVIDENCE"
    RETRIEVAL_LIMIT_EXCEEDED = "RETRIEVAL_LIMIT_EXCEEDED"
    RETRIEVAL_TIMEOUT = "RETRIEVAL_TIMEOUT"
    RETRIEVAL_CANCELLED = "RETRIEVAL_CANCELLED"
    CONTEXT_BUDGET_EXCEEDED = "CONTEXT_BUDGET_EXCEEDED"
    INVALID_REQUEST = "INVALID_REQUEST"
    INVARIANT_FAILURE = "INVARIANT_FAILURE"


class RetrievalStage(StrEnum):
    """Receipt appendix - the exact eleven ordered stage names."""

    REQUEST_VALIDATED = "REQUEST_VALIDATED"
    AUTHENTICATED = "AUTHENTICATED"
    PERMISSION_AUTHORIZED = "PERMISSION_AUTHORIZED"
    ASSIGNMENT_AUTHORIZED = "ASSIGNMENT_AUTHORIZED"
    CORPUS_RESOLVED = "CORPUS_RESOLVED"
    SOURCES_READ = "SOURCES_READ"
    P3C_ADMITTED = "P3C_ADMITTED"
    MATCHED_AND_RANKED = "MATCHED_AND_RANKED"
    REVALIDATED = "REVALIDATED"
    PROJECTED = "PROJECTED"
    RECEIPT_EMITTED = "RECEIPT_EMITTED"


RETRIEVAL_STAGE_ORDER: tuple[RetrievalStage, ...] = tuple(RetrievalStage)


class StageOutcome(StrEnum):
    """Receipt appendix - the exact four closed stage outcomes."""

    PASS = "PASS"
    DENY = "DENY"
    FAIL = "FAIL"
    NOT_RUN = "NOT_RUN"


class StageReasonCode(StrEnum):
    """Receipt appendix - reason codes allowed for DENY/FAIL stages: the
    eight R2 request-failure codes, AUTHENTICATION_FAILED, ACCESS_DENIED, and
    every negative R11 outcome literal other than INVALID_REQUEST."""

    REQUEST_SHAPE_INVALID = "REQUEST_SHAPE_INVALID"
    QUERY_INVALID = "QUERY_INVALID"
    QUERY_LIMIT_EXCEEDED = "QUERY_LIMIT_EXCEEDED"
    CORPUS_ID_INVALID = "CORPUS_ID_INVALID"
    FILTER_INVALID = "FILTER_INVALID"
    FILTER_WIDENS_SCOPE = "FILTER_WIDENS_SCOPE"
    RESULT_LIMIT_INVALID = "RESULT_LIMIT_INVALID"
    CONTEXT_BUDGET_INVALID = "CONTEXT_BUDGET_INVALID"
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    ACCESS_DENIED = "ACCESS_DENIED"
    CORPUS_UNAVAILABLE = "CORPUS_UNAVAILABLE"
    STALE_EVIDENCE = "STALE_EVIDENCE"
    RETRIEVAL_LIMIT_EXCEEDED = "RETRIEVAL_LIMIT_EXCEEDED"
    RETRIEVAL_TIMEOUT = "RETRIEVAL_TIMEOUT"
    RETRIEVAL_CANCELLED = "RETRIEVAL_CANCELLED"
    CONTEXT_BUDGET_EXCEEDED = "CONTEXT_BUDGET_EXCEEDED"
    INVARIANT_FAILURE = "INVARIANT_FAILURE"
    NO_EVIDENCE = "NO_EVIDENCE"


TOKEN_ESTIMATE_METHOD = "UTF8_BYTES_DIV_2_ESTIMATE_V1"
