from enum import StrEnum


class SourceType(StrEnum):
    PROJECT_KNOWLEDGE = "PROJECT_KNOWLEDGE"
    INTERNAL_MESSAGE = "INTERNAL_MESSAGE"
    EXTERNAL_UNTRUSTED_FIXTURE = "EXTERNAL_UNTRUSTED_FIXTURE"


class Sensitivity(StrEnum):
    PUBLIC = "PUBLIC"
    INTERNAL = "INTERNAL"
    CONFIDENTIAL = "CONFIDENTIAL"
    RESTRICTED = "RESTRICTED"


SENSITIVITY_ORDER = {value: index for index, value in enumerate(Sensitivity)}


class Disposition(StrEnum):
    CANDIDATE_READY = "CANDIDATE_READY"
    NO_CANDIDATE_DUPLICATE = "NO_CANDIDATE_DUPLICATE"
    NO_CANDIDATE_QUARANTINED = "NO_CANDIDATE_QUARANTINED"
    NO_CANDIDATE_FALLBACK = "NO_CANDIDATE_FALLBACK"


class Stage(StrEnum):
    ENVELOPE = "ENVELOPE"
    NORMALIZATION = "NORMALIZATION"
    TERMINOLOGY = "TERMINOLOGY"
    CLASSIFICATION = "CLASSIFICATION"
    CONFLICT = "CONFLICT"
    REDACTION = "REDACTION"
    DEDUPE = "DEDUPE"
    QUALITY = "QUALITY"
    CANDIDATE_ADMISSION = "CANDIDATE_ADMISSION"


STAGE_ORDER = tuple(Stage)


class StageOutcome(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    NOT_RUN = "NOT_RUN"


class DedupeStatus(StrEnum):
    UNIQUE = "UNIQUE"
    EXACT_SOURCE_MATCH = "EXACT_SOURCE_MATCH"
    REDACTED_TEXT_MATCH = "REDACTED_TEXT_MATCH"
    DIGEST_COLLISION_SUSPECTED = "DIGEST_COLLISION_SUSPECTED"
    INSUFFICIENT_CONTEXT = "INSUFFICIENT_CONTEXT"


class StageReason(StrEnum):
    STAGE_PASS = "STAGE_PASS"
    PROVENANCE_MISMATCH = "PROVENANCE_MISMATCH"
    UNSUPPORTED_TRANSFORM = "UNSUPPORTED_TRANSFORM"
    POLICY_DRIFT = "POLICY_DRIFT"
    AMBIGUOUS_LOCAL_TIME = "AMBIGUOUS_LOCAL_TIME"
    AMBIGUOUS_ACTION_STATE = "AMBIGUOUS_ACTION_STATE"
    CONFLICT_DETECTED = "CONFLICT_DETECTED"
    REDACTION_FAILED = "REDACTION_FAILED"
    REDACTION_RESIDUE = "REDACTION_RESIDUE"
    DEDUPE_CONTEXT_INVALID = "DEDUPE_CONTEXT_INVALID"
    EXACT_SOURCE_MATCH = "EXACT_SOURCE_MATCH"
    DIGEST_COLLISION_SUSPECTED = "DIGEST_COLLISION_SUSPECTED"
    INSUFFICIENT_CONTEXT = "INSUFFICIENT_CONTEXT"
    QUALITY_INCOMPLETE = "QUALITY_INCOMPLETE"
    STAGE_UNAVAILABLE = "STAGE_UNAVAILABLE"
    STAGE_INVARIANT_ERROR = "STAGE_INVARIANT_ERROR"
    PRIOR_STAGE_FAILED = "PRIOR_STAGE_FAILED"


class QuarantineReason(StrEnum):
    PROVENANCE_MISMATCH = "PROVENANCE_MISMATCH"
    AMBIGUOUS_VALUE = "AMBIGUOUS_VALUE"
    UNSUPPORTED_TRANSFORM = "UNSUPPORTED_TRANSFORM"
    DEDUPE_CONTEXT_INVALID = "DEDUPE_CONTEXT_INVALID"
    DIGEST_COLLISION_SUSPECTED = "DIGEST_COLLISION_SUSPECTED"
    POLICY_DRIFT = "POLICY_DRIFT"
    REDACTION_FAILED = "REDACTION_FAILED"
    REDACTION_RESIDUE = "REDACTION_RESIDUE"
    CONFLICT_DETECTED = "CONFLICT_DETECTED"
    QUALITY_INCOMPLETE = "QUALITY_INCOMPLETE"
    STAGE_INVARIANT_ERROR = "STAGE_INVARIANT_ERROR"


class FallbackReason(StrEnum):
    QUARANTINE_ROUTE_UNAVAILABLE = "QUARANTINE_ROUTE_UNAVAILABLE"
    STAGE_UNAVAILABLE = "STAGE_UNAVAILABLE"
    STAGE_INVARIANT_ERROR = "STAGE_INVARIANT_ERROR"


class SafeErrorCode(StrEnum):
    INVALID_SCHEMA_VERSION = "INVALID_SCHEMA_VERSION"
    FIELD_SET_MISMATCH = "FIELD_SET_MISMATCH"
    INVALID_SOURCE_ID = "INVALID_SOURCE_ID"
    INVALID_SOURCE_VERSION = "INVALID_SOURCE_VERSION"
    INVALID_SOURCE_LINK = "INVALID_SOURCE_LINK"
    INVALID_SOURCE_TYPE = "INVALID_SOURCE_TYPE"
    INVALID_RAW_TEXT = "INVALID_RAW_TEXT"
    INVALID_RECEIVED_AT = "INVALID_RECEIVED_AT"
    INVALID_DECLARED_SENSITIVITY = "INVALID_DECLARED_SENSITIVITY"
    INVALID_SOURCE_OWNER_ID = "INVALID_SOURCE_OWNER_ID"
    INVALID_SOURCE_FINGERPRINT = "INVALID_SOURCE_FINGERPRINT"
