from enum import StrEnum


class TruthClass(StrEnum):
    CANONICAL_OPERATIONAL_RECORD = "CANONICAL_OPERATIONAL_RECORD"
    ADVISORY_SOURCE_EVIDENCE = "ADVISORY_SOURCE_EVIDENCE"


class RecordType(StrEnum):
    OPERATIONAL_EVENT = "OperationalEvent"
    TASK = "Task"
    CUSTOMER_REQUEST = "CustomerRequest"
    INCIDENT = "Incident"
    HANDOVER = "Handover"
    REPORT = "Report"
    MESSAGE = "Message"
    PROJECT_KNOWLEDGE = "PROJECT_KNOWLEDGE"


class VersionKind(StrEnum):
    INTEGER_VERSION = "INTEGER_VERSION"
    SOURCE_VERSION_STRING = "SOURCE_VERSION_STRING"
    UNVERSIONED = "UNVERSIONED"


class RetentionDisposition(StrEnum):
    OWNER_ASSERTED_ACTIVE = "OWNER_ASSERTED_ACTIVE"
    OWNER_ASSERTED_EXPIRED = "OWNER_ASSERTED_EXPIRED"
    OWNER_ASSERTED_ERASED = "OWNER_ASSERTED_ERASED"
    OWNER_NOT_FOUND = "OWNER_NOT_FOUND"


class TenantScopeStatus(StrEnum):
    NOT_MODELED = "NOT_MODELED"


class DataScopeStatus(StrEnum):
    NOT_EVALUATED = "NOT_EVALUATED"


class ResultKind(StrEnum):
    RETRIEVAL_READY = "RETRIEVAL_READY"
    NOT_ADMITTED = "NOT_ADMITTED"


class NonAdmissionReason(StrEnum):
    REFINERY_RESULT_NOT_READY = "REFINERY_RESULT_NOT_READY"
    CANDIDATE_BINDING_MISMATCH = "CANDIDATE_BINDING_MISMATCH"
    UNKNOWN_SOURCE_TYPE = "UNKNOWN_SOURCE_TYPE"
    SOURCE_NOT_ELIGIBLE = "SOURCE_NOT_ELIGIBLE"
    SOURCE_VERSION_INVALID = "SOURCE_VERSION_INVALID"
    SOURCE_DIGEST_OWNER_MISSING = "SOURCE_DIGEST_OWNER_MISSING"
    SOURCE_DIGEST_MISMATCH = "SOURCE_DIGEST_MISMATCH"
    SOURCE_PROJECTION_MISMATCH = "SOURCE_PROJECTION_MISMATCH"
    SCOPE_INVALID = "SCOPE_INVALID"
    TENANT_SCOPE_NOT_MODELED = "TENANT_SCOPE_NOT_MODELED"
    LIFECYCLE_INVALID = "LIFECYCLE_INVALID"
    STALE_SOURCE = "STALE_SOURCE"
    RETENTION_OWNER_NOT_FOUND = "RETENTION_OWNER_NOT_FOUND"
    RETENTION_NOT_ACTIVE = "RETENTION_NOT_ACTIVE"
    PROVENANCE_INVALID = "PROVENANCE_INVALID"
    DATA_SCOPE_EVIDENCE_INVALID = "DATA_SCOPE_EVIDENCE_INVALID"
    CONTRACT_VERSION_UNSUPPORTED = "CONTRACT_VERSION_UNSUPPORTED"
    INVARIANT_VIOLATION = "INVARIANT_VIOLATION"
