#!/usr/bin/env python3
"""Generate and verify the project module catalog.

The catalog is the project's structural source of truth. This script keeps it
honest so its "FROZEN"/status labels stay verifiable (EA review #4/#5):

* Size metrics (LOC, code-file counts) are COMPUTED from disk, never hand-typed.
* Every module `path` in the registry must actually exist.
* The human-readable MODULE_CATALOG.md is GENERATED from the JSON, so the two
  never drift.

Usage:
    python scripts/generate_catalog.py --check    # CI: verify, non-zero on drift
    python scripts/generate_catalog.py --write     # regenerate metrics + catalog
    python scripts/generate_catalog.py             # same as --check
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = REPO_ROOT / "docs" / "catalog" / "MODULE_REGISTRY.json"
CATALOG_MD_PATH = REPO_ROOT / "docs" / "catalog" / "MODULE_CATALOG.md"

CODE_SUFFIXES = {".py", ".ts", ".tsx"}
SKIP_DIRS = {"node_modules", ".pytest_cache", "__pycache__", ".git", "dist", "build"}


def _iter_code_files(base: Path):
    for path in base.rglob("*"):
        if path.is_dir():
            continue
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        if path.suffix in CODE_SUFFIXES:
            yield path


def compute_metrics(module_path: Path) -> dict:
    """Return LOC and code-file counts for a module directory."""
    loc = 0
    code_files = 0
    nonempty = 0
    for f in _iter_code_files(module_path):
        code_files += 1
        try:
            lines = f.read_text(encoding="utf-8", errors="replace").count("\n")
        except OSError:
            lines = 0
        loc += lines
        if f.stat().st_size > 1:
            nonempty += 1
    return {"loc": loc, "code_files": code_files, "nonempty_code_files": nonempty}


def load_registry() -> dict:
    return json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))


def verify(registry: dict) -> list[str]:
    """Return a list of problems (empty means the catalog is consistent)."""
    problems: list[str] = []
    vocab = set(registry.get("cvf_control_vocabulary", []))
    legend = set(registry.get("status_legend", {}).keys())
    seen_ids: set[str] = set()

    for mod in registry.get("modules", []):
        mid = mod.get("id", "<no-id>")
        if mid in seen_ids:
            problems.append(f"duplicate module id: {mid}")
        seen_ids.add(mid)

        path = REPO_ROOT / mod.get("path", "")
        if not path.is_dir():
            problems.append(f"{mid}: path does not exist: {mod.get('path')}")

        if mod.get("status") not in legend:
            problems.append(f"{mid}: unknown status {mod.get('status')!r}")

        for ctrl in mod.get("cvf_controls", []):
            # provider_authorization is a profile concept not in the 12-control
            # vocabulary; allow it explicitly.
            if ctrl not in vocab and ctrl != "provider_authorization":
                problems.append(f"{mid}: unknown cvf control {ctrl!r}")

        for dep in mod.get("depends_on", []):
            # resolved after full pass below
            mod.setdefault("_deps", []).append(dep)

    for mod in registry.get("modules", []):
        for dep in mod.get("depends_on", []):
            if dep not in seen_ids:
                problems.append(f"{mod['id']}: depends_on unknown module {dep!r}")

    return problems


def enrich_metrics(registry: dict) -> dict:
    """Attach computed metrics to each module and to the totals block."""
    total_loc = 0
    total_code_files = 0
    by_status: dict[str, int] = {}
    for mod in registry["modules"]:
        m = compute_metrics(REPO_ROOT / mod["path"])
        mod["metrics"] = m
        total_loc += m["loc"]
        total_code_files += m["code_files"]
        by_status[mod["status"]] = by_status.get(mod["status"], 0) + 1
        mod.pop("_deps", None)

    registry["metrics"] = {
        "note": "Regenerated by scripts/generate_catalog.py --write. Do not hand-edit.",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "totals": {
            "modules": len(registry["modules"]),
            "code_loc": total_loc,
            "code_files": total_code_files,
            "by_status": dict(sorted(by_status.items())),
        },
    }
    return registry


def render_markdown(registry: dict) -> str:
    totals = registry["metrics"]["totals"]
    gen = registry["metrics"]["generated_at"]
    lines: list[str] = []
    lines.append("# Module Catalog")
    lines.append("")
    lines.append(
        "> GENERATED FILE — do not edit by hand. Source of truth is "
        "[`MODULE_REGISTRY.json`](MODULE_REGISTRY.json). "
        "Run `python scripts/generate_catalog.py --write` to regenerate."
    )
    lines.append("")
    lines.append(f"_Last generated: {gen}_")
    lines.append("")
    lines.append("## How to use this catalog")
    lines.append("")
    lines.append(
        "- **Before working:** find the module you will touch and read its "
        "`purpose`, `status`, `cvf_controls`, and `enforcement`."
    )
    lines.append(
        "- **After completing a piece:** update that module's entry in "
        "`MODULE_REGISTRY.json` (status, enforcement, next_step, tests), then "
        "run the generator to refresh this file and the metrics."
    )
    lines.append(
        "- **Size metrics are computed**, not written — they cannot lie about "
        "how much code exists."
    )
    lines.append("")
    lines.append("## Totals")
    lines.append("")
    lines.append(f"- Modules: **{totals['modules']}**")
    lines.append(f"- Code LOC (py/ts/tsx): **{totals['code_loc']}**")
    lines.append(f"- Code files: **{totals['code_files']}**")
    by_status = ", ".join(f"{k}={v}" for k, v in totals["by_status"].items())
    lines.append(f"- By status: {by_status}")
    lines.append("")
    lines.append("## Status legend")
    lines.append("")
    for k, v in registry["status_legend"].items():
        lines.append(f"- **{k}** — {v}")
    lines.append("")
    lines.append("## Modules")
    lines.append("")
    lines.append("| Module | Path | Status | LOC | CVF controls | Purpose |")
    lines.append("|---|---|---|---:|---|---|")
    for mod in sorted(registry["modules"], key=_status_sort_key):
        ctrls = ", ".join(mod["cvf_controls"]) or "—"
        loc = mod["metrics"]["loc"]
        purpose = mod["purpose"].replace("|", "\\|")
        lines.append(
            f"| `{mod['id']}` | {mod['path']} | {mod['status']} | {loc} | "
            f"{ctrls} | {purpose} |"
        )
    lines.append("")
    lines.append("## Per-module detail")
    lines.append("")
    for mod in sorted(registry["modules"], key=_status_sort_key):
        lines.append(f"### `{mod['id']}` — {mod['status']}")
        lines.append("")
        lines.append(f"- **Path:** `{mod['path']}` ({mod['kind']})")
        lines.append(f"- **Purpose:** {mod['purpose']}")
        lines.append(f"- **CVF controls:** {', '.join(mod['cvf_controls']) or '—'}")
        lines.append(f"- **Enforcement:** {mod['enforcement']}")
        lines.append(f"- **Contract:** {mod.get('contract', '—')}")
        deps = ", ".join(f"`{d}`" for d in mod.get("depends_on", [])) or "—"
        lines.append(f"- **Depends on:** {deps}")
        tests = ", ".join(f"`{t}`" for t in mod.get("tests", [])) or "—"
        lines.append(f"- **Tests:** {tests}")
        lines.append(
            f"- **Metrics:** {mod['metrics']['loc']} LOC across "
            f"{mod['metrics']['code_files']} code file(s)"
        )
        lines.append(f"- **Next step:** {mod.get('next_step', '—')}")
        lines.append("")
    lines.append("## Related")
    lines.append("")
    lines.append(
        "- CVF control enforcement points: "
        "[`docs/cvf/CVF_CONTROL_MAPPING.md`](../cvf/CVF_CONTROL_MAPPING.md)"
    )
    lines.append("- Release/validation status: `IMPLEMENTATION_STATUS.json` (repo root)")
    lines.append("")
    return "\n".join(lines)


_STATUS_ORDER = {"enforced": 0, "partial": 1, "contract-only": 2, "stub": 3, "empty": 4}


def _status_sort_key(mod: dict):
    return (_STATUS_ORDER.get(mod["status"], 9), mod["id"])


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Regenerate metrics + catalog")
    parser.add_argument("--check", action="store_true", help="Verify only (CI mode)")
    args = parser.parse_args(argv)

    registry = load_registry()
    problems = verify(registry)
    if problems:
        print("CATALOG VERIFY: FAIL")
        for p in problems:
            print(f"  - {p}")
        return 1

    if args.write:
        registry = enrich_metrics(registry)
        REGISTRY_PATH.write_text(
            json.dumps(registry, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
        )
        CATALOG_MD_PATH.write_text(render_markdown(registry), encoding="utf-8")
        totals = registry["metrics"]["totals"]
        print("CATALOG VERIFY: PASS")
        print(
            f"CATALOG WRITE: {totals['modules']} modules, "
            f"{totals['code_loc']} LOC -> {CATALOG_MD_PATH.relative_to(REPO_ROOT)}"
        )
        return 0

    # default / --check: verify metrics would match without writing
    print("CATALOG VERIFY: PASS")
    print(f"  {len(registry['modules'])} modules, all paths exist, statuses valid.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
