#!/usr/bin/env python3
"""Generate and verify the project module catalog.

The catalog is the project's structural source of truth. This script keeps it
honest so its "FROZEN"/status labels stay verifiable (EA review #4/#5):

* Size metrics (LOC, code-file counts) are COMPUTED from disk, never hand-typed.
* Every module `path` in the registry must actually exist.
* The human-readable MODULE_CATALOG_DETAIL.md is GENERATED from the detailed JSON, so the two
  never drift.

Usage:
    python scripts/generate_catalog.py --check    # CI: verify, non-zero on drift
    python scripts/generate_catalog.py --write     # regenerate metrics + catalog
    python scripts/generate_catalog.py             # same as --check
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = REPO_ROOT / "docs" / "catalog" / "MODULE_REGISTRY_DETAIL.json"
CATALOG_MD_PATH = REPO_ROOT / "docs" / "catalog" / "MODULE_CATALOG_DETAIL.md"

CODE_SUFFIXES = {".py", ".ts", ".tsx"}
SKIP_DIRS = {"node_modules", ".pytest_cache", "__pycache__", ".git", "dist", "build"}


def _iter_code_files(base: Path):
    for path in base.rglob("*"):
        if path.is_dir():
            continue
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        if path.suffix in CODE_SUFFIXES:
            yield path


def compute_metrics(module_path: Path) -> dict:
    """Return LOC and code-file counts for a module directory."""
    loc = 0
    code_files = 0
    nonempty = 0
    for f in _iter_code_files(module_path):
        code_files += 1
        try:
            lines = f.read_text(encoding="utf-8", errors="replace").count("\n")
        except OSError:
            lines = 0
        loc += lines
        if f.stat().st_size > 1:
            nonempty += 1
    return {"loc": loc, "code_files": code_files, "nonempty_code_files": nonempty}


def load_registry() -> dict:
    return json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))


def verify(registry: dict) -> list[str]:
    """Return a list of problems (empty means the catalog is consistent)."""
    problems: list[str] = []
    vocab = set(registry.get("cvf_control_vocabulary", []))
    legend = set(registry.get("status_legend", {}).keys())
    seen_ids: set[str] = set()

    for mod in registry.get("modules", []):
        mid = mod.get("id", "<no-id>")
        if mid in seen_ids:
            problems.append(f"duplicate module id: {mid}")
        seen_ids.add(mid)

        path = REPO_ROOT / mod.get("path", "")
        if not path.is_dir():
            problems.append(f"{mid}: path does not exist: {mod.get('path')}")

        if mod.get("status") not in legend:
            problems.append(f"{mid}: unknown status {mod.get('status')!r}")

        for ctrl in mod.get("cvf_controls", []):
            # provider_authorization is a profile concept not in the 12-control
            # vocabulary; allow it explicitly.
            if ctrl not in vocab and ctrl != "provider_authorization":
                problems.append(f"{mid}: unknown cvf control {ctrl!r}")

        for dep in mod.get("depends_on", []):
            # resolved after full pass below
            mod.setdefault("_deps", []).append(dep)

    for mod in registry.get("modules", []):
        for dep in mod.get("depends_on", []):
            if dep not in seen_ids:
                problems.append(f"{mod['id']}: depends_on unknown module {dep!r}")

    return problems


def enrich_metrics(registry: dict, *, generated_at: str | None = None) -> dict:
    """Attach computed metrics to each module and to the totals block.

    ``generated_at`` lets --check recompute metrics deterministically against
    the SAME timestamp already stored in the registry, so the comparison in
    --check is about whether the NUMBERS match, not whether the clock moved.
    --write always stamps a fresh timestamp (the normal "this is current as
    of now" meaning).
    """
    total_loc = 0
    total_code_files = 0
    by_status: dict[str, int] = {}
    for mod in registry["modules"]:
        m = compute_metrics(REPO_ROOT / mod["path"])
        mod["metrics"] = m
        total_loc += m["loc"]
        total_code_files += m["code_files"]
        by_status[mod["status"]] = by_status.get(mod["status"], 0) + 1
        mod.pop("_deps", None)

    registry["metrics"] = {
        "note": "Regenerated by scripts/generate_catalog.py --write. Do not hand-edit.",
        "generated_at": generated_at or datetime.now(timezone.utc).isoformat(),
        "totals": {
            "modules": len(registry["modules"]),
            "code_loc": total_loc,
            "code_files": total_code_files,
            "by_status": dict(sorted(by_status.items())),
        },
    }
    return registry


from catalog_markdown import render_markdown


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Regenerate metrics + catalog")
    parser.add_argument("--check", action="store_true", help="Verify only (CI mode)")
    args = parser.parse_args(argv)

    registry = load_registry()
    problems = verify(registry)
    if problems:
        print("CATALOG VERIFY: FAIL")
        for p in problems:
            print(f"  - {p}")
        return 1

    if args.write:
        registry = enrich_metrics(registry)
        REGISTRY_PATH.write_text(
            json.dumps(registry, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n"
        )
        CATALOG_MD_PATH.write_text(render_markdown(registry), encoding="utf-8", newline="\n")
        totals = registry["metrics"]["totals"]
        print("CATALOG VERIFY: PASS")
        print(
            f"CATALOG WRITE: {totals['modules']} modules, "
            f"{totals['code_loc']} LOC -> {CATALOG_MD_PATH.relative_to(REPO_ROOT)}"
        )
        return 0

    # --check: recompute metrics and Markdown IN MEMORY (pinning generated_at
    # to the stored value so only the numbers are compared, not the clock),
    # then diff against what's actually on disk. This is the fix for
    # EA_INDEPENDENT_REVIEW_2026-07-22_CODEX.md Medium Finding #6: the
    # previous --check never called enrich_metrics/render_markdown at all, so
    # a hand-edited (wrong) code_loc value still passed.
    stored_generated_at = registry.get("metrics", {}).get("generated_at")
    stored_metrics = json.loads(json.dumps(registry.get("metrics", {})))
    stored_module_metrics = {
        m["id"]: m.get("metrics") for m in registry.get("modules", [])
    }
    stored_markdown = CATALOG_MD_PATH.read_text(encoding="utf-8") if CATALOG_MD_PATH.is_file() else None

    recomputed = json.loads(json.dumps(registry))  # deep copy, don't mutate `registry`
    recomputed = enrich_metrics(recomputed, generated_at=stored_generated_at)

    drift: list[str] = []
    if stored_metrics.get("totals") != recomputed["metrics"]["totals"]:
        drift.append(
            f"catalog totals are stale: registry says {stored_metrics.get('totals')}, "
            f"recomputed is {recomputed['metrics']['totals']}"
        )
    for mod in recomputed["modules"]:
        stored_m = stored_module_metrics.get(mod["id"])
        if stored_m != mod["metrics"]:
            drift.append(
                f"{mod['id']}: metrics are stale: registry says {stored_m}, "
                f"recomputed is {mod['metrics']}"
            )

    recomputed_markdown = render_markdown(recomputed)
    if stored_markdown is None:
        drift.append(f"missing: {CATALOG_MD_PATH.relative_to(REPO_ROOT)}")
    elif stored_markdown != recomputed_markdown:
        drift.append(
            f"{CATALOG_MD_PATH.relative_to(REPO_ROOT)} does not match what "
            f"MODULE_REGISTRY_DETAIL.json would generate - run "
            f"`python scripts/generate_catalog.py --write`"
        )

    if drift:
        print("CATALOG VERIFY: FAIL")
        for d in drift:
            print(f"  - {d}")
        return 1

    print("CATALOG VERIFY: PASS")
    print(
        f"  {len(registry['modules'])} modules, all paths exist, statuses valid, "
        f"metrics and Markdown are up to date."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
